import type { Bundle } from "./types"

export const sampleBundles: Bundle[] = [
  {
    id: "1",
    name: "Essential Kitchen Bundle",
    description: "Perfect starter pack for your kitchen needs",
    price: 50000,
    type: "kitchen",
    vendorId: "v1",
    vendorName: "Fresh Mart Lagos",
    image: "/kitchen-essentials-rice-beans-oil.jpg",
    rating: 4.8,
    reviewCount: 124,
    items: [
      { id: "1", name: "Rice", quantity: "10", unit: "kg" },
      { id: "2", name: "Beans", quantity: "5", unit: "kg" },
      { id: "3", name: "Palm Oil", quantity: "3", unit: "L" },
      { id: "4", name: "Vegetable Oil", quantity: "2", unit: "L" },
    ],
  },
  {
    id: "2",
    name: "Premium Kitchen Bundle",
    description: "Complete kitchen stock-up for the month",
    price: 100000,
    type: "kitchen",
    vendorId: "v2",
    vendorName: "Abuja Food Hub",
    image: "/premium-kitchen-bundle-groceries.jpg",
    rating: 4.9,
    reviewCount: 89,
    items: [
      { id: "1", name: "Rice", quantity: "25", unit: "kg" },
      { id: "2", name: "Beans", quantity: "10", unit: "kg" },
      { id: "3", name: "Palm Oil", quantity: "5", unit: "L" },
      { id: "4", name: "Vegetable Oil", quantity: "5", unit: "L" },
      { id: "5", name: "Garri", quantity: "10", unit: "kg" },
      { id: "6", name: "Tomato Paste", quantity: "12", unit: "cans" },
    ],
  },
  {
    id: "3",
    name: "Farm Starter Pack",
    description: "Essential supplies for small-scale farming",
    price: 75000,
    type: "farm",
    vendorId: "v3",
    vendorName: "AgriSupply Nigeria",
    image: "/farm-supplies-seeds-fertilizer.jpg",
    rating: 4.7,
    reviewCount: 56,
    items: [
      { id: "1", name: "Maize Seeds", quantity: "5", unit: "kg" },
      { id: "2", name: "Fertilizer", quantity: "50", unit: "kg" },
      { id: "3", name: "Pesticide", quantity: "2", unit: "L" },
      { id: "4", name: "Garden Tools Set", quantity: "1", unit: "set" },
    ],
  },
  {
    id: "4",
    name: "Livestock Bundle",
    description: "Quality livestock for your farm",
    price: 150000,
    type: "livestock",
    vendorId: "v4",
    vendorName: "Kano Livestock Farm",
    image: "/chickens-poultry-farm-livestock.jpg",
    rating: 4.6,
    reviewCount: 34,
    items: [
      { id: "1", name: "Broiler Chickens", quantity: "20", unit: "birds" },
      { id: "2", name: "Chicken Feed", quantity: "50", unit: "kg" },
      { id: "3", name: "Vitamins & Supplements", quantity: "1", unit: "pack" },
    ],
  },
  {
    id: "5",
    name: "Budget Kitchen Bundle",
    description: "Affordable essentials for your kitchen",
    price: 30000,
    type: "kitchen",
    vendorId: "v1",
    vendorName: "Fresh Mart Lagos",
    image: "/budget-groceries-affordable-food.jpg",
    rating: 4.5,
    reviewCount: 201,
    items: [
      { id: "1", name: "Rice", quantity: "5", unit: "kg" },
      { id: "2", name: "Beans", quantity: "3", unit: "kg" },
      { id: "3", name: "Vegetable Oil", quantity: "1", unit: "L" },
      { id: "4", name: "Salt", quantity: "1", unit: "kg" },
    ],
  },
  {
    id: "6",
    name: "Advanced Farm Bundle",
    description: "Professional farming equipment and supplies",
    price: 200000,
    type: "farm",
    vendorId: "v3",
    vendorName: "AgriSupply Nigeria",
    image: "/professional-farm-equipment-tractor.jpg",
    rating: 4.8,
    reviewCount: 42,
    items: [
      { id: "1", name: "Irrigation System", quantity: "1", unit: "set" },
      { id: "2", name: "Premium Seeds Mix", quantity: "10", unit: "kg" },
      { id: "3", name: "Organic Fertilizer", quantity: "100", unit: "kg" },
      { id: "4", name: "Farm Tools Kit", quantity: "1", unit: "set" },
    ],
  },
]
